OIU.CorporateWebsite.Portal/Areas/webadmin/Controllers/ProductController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using OIU.CorporateWebsite.BLL;
using OIU.CorporateWebsite.Model;

namespace OIU.CorporateWebsite.Portal.Areas.webadmin.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IBLL.IProductService _productService = new ProductService();
        private readonly IBLL.IPCategoryService _pCategoryService = new PCategoryService();
        public ActionResult Index()
        {
            ViewBag.PCategoryList = _pCategoryService.LoadEntities(m => m.Pid == 0);
            return View();
        }
        /// <summary>
        /// 根据ID获得产品信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult GetProductInfo(int id)
        {
            var productInfo = _productService.LoadEntities(m => m.ID == id).FirstOrDefault();
            return Json(productInfo, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetAllProduct()
        {
            int pageIndex = Request["page"] == null ? 1 : int.Parse(Request["page"]);
            int pageSize = Request["rows"] == null ? 10 : int.Parse(Request["rows"]);
            string PName = Request["PName"];
            var PCid = 0;
            int.TryParse(Request["PCid"], out PCid);

            int total = 0;

            var temp = _productService.LoadEntities(m => true);
            if (!string.IsNullOrEmpty(PName))
            {
                temp = temp.Where<Product>(u => u.PName.Contains(PName));
            }
            if (PCid != 0)
            {
                temp = temp.Where<Product>(u => u.PCid == PCid);
            }
            //var t = _productService.LoadEntities(m => true).Select(m => new
            //{
            //    m.ID,
            //    m.PCid,
            //    m.PContent,
            //    m.PImg,
            //    m.PName,
            //    CategoryName = _pCategoryService.LoadEntities(c => c.ID == m.PCid).FirstOrDefault().CName
            //}).ToList();
            total = temp.Count();
            var data = temp.OrderBy(u => u.ID).Skip(pageSize * (pageIndex - 1)).Take(pageSize);
            //构造成Json的格式传递
            var result = new { total = total, rows = data };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdateProductInfo(Product info)
        {
            var productInfo = _productService.LoadEntities(m => m.ID == info.ID).FirstOrDefault();
            if (productInfo == null)
            {
                return Content("错误信息，请您检查");
            }

            productInfo.PCid = info.PCid;
            productInfo.PContent = info.PContent;
            productInfo.PImg = info.PImg;
            productInfo.PName = info.PName;
            productInfo.IsRecommend = info.IsRecommend;

            _productService.UpdateEntity(productInfo);
            return Content("ok");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddProduct(Product info)
        {
            if (info == null)
            {
                return Content("错误信息，请您检查");
            }
            info.AddTime = DateTime.Now;
            _productService.AddEntity(info);
            return Content("ok");
        }

        [HttpPost]
        public ActionResult DeleteProduct(Product info)
        {
            var productInfo = _productService.LoadEntities(m => m.ID == info.ID).FirstOrDefault();
            if (productInfo == null)
            {
                return Content("错误信息，请您检查");
            }
            _productService.DeleteProduct(productInfo);
            return Content("ok");

        }


    }
}

OIU.CorporateWebsite.Portal/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OIU.CorporateWebsite.BLL;
using OIU.MvcPager;

namespace OIU.CorporateWebsite.Portal.Controllers
{
    public class ProductController : Controller
    {
        private readonly IBLL.IProductService _productService=new ProductService();
        private readonly IBLL.IPCategoryService _pCategoryService=new PCategoryService();

        public ActionResult Index(int id=1)
        {
            return View(_productService.LoadEntities(m => true).OrderByDescending(m => m.AddTime).ToPagedList(id, 10));
        }

        public ActionResult Category(int cid,int pageIndex=1)
        {
            var pc = _pCategoryService.LoadEntities(m => m.ID == cid).FirstOrDefault();
            if (pc == null)
            {
                RedirectToAction("Index");
            }
            ViewBag.pc = pc;
            return View(_productService.LoadEntities(m => m.PCid==cid).OrderByDescending(m => m.AddTime).ToPagedList(pageIndex, 10));
        }

        public ActionResult Details(int id, int pageIndex = 1)
        {
            var model = _productService.LoadEntities(m => m.ID == id).FirstOrDefault();
            if (model == null)
            {
                RedirectToAction("Index");
            }
            var pc = _pCategoryService.LoadEntities(m => m.ID == model.PCid).FirstOrDefault();
            if (pc == null)
            {
                RedirectToAction("Index");
            }
            var prelation = _productService.LoadEntities(m => (m.PCid == model.PCid && m.ID != model.ID)).OrderByDescending(m => m.AddTime).ToPagedList(pageIndex, 6);
            ViewBag.prelation = prelation;
            ViewBag.pc = pc;
            return View(model);
        }

    }
}

OIU.CorporateWebsite.Portal/Controllers/SiteConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OIU.CorporateWebsite.BLL;
using OIU.CorporateWebsite.Model;

namespace OIU.CorporateWebsite.Portal.Controllers
{
    public class SiteConfigController : Controller
    {
        private readonly IBLL.ISiteConfigService _siteConfigService = new SiteConfigService();
        private readonly IBLL.IBannerService _bannerService = new BannerService();
        private readonly IBLL.IPCategoryService _pCategoryService = new PCategoryService();
        private readonly IBLL.IAboutService _aboutService = new AboutService();

        private SiteConfig getModel()
        {
            return _siteConfigService.LoadEntities(m => m.ID == 1).FirstOrDefault();
        }
        [OutputCache(Duration = 60)]
        public ActionResult Seo()
        {
            return PartialView("_PartialSeo", getModel());
        }
        [OutputCache(Duration = 60)]
        public ActionResult Logo()
        {
            return PartialView("_PartialLogo", getModel());
        }

        [OutputCache(Duration = 60)]
        public ActionResult Footer()
        {
            return Content(getModel().SiteFooter);
        }

        [OutputCache(Duration = 60)]
        public ActionResult Banner()
        {
            ViewBag.bannerList = _bannerService.LoadEntities(m => m.ImgCategory == "Banner");
            ViewBag.pcategoryList = _pCategoryService.LoadEntities(m => true);
            return PartialView("_PartialBanner");
        }

        [OutputCache(Duration = 60)]
        public ActionResult SiteLeft()
        {
            ViewBag.pcategoryList = _pCategoryService.LoadEntities(m => true);
            var info = _aboutService.LoadEntities(m => m.ID == 5).FirstOrDefault();
            return PartialView("_PartialLeft", info);
        }

    }
}

OIU.CorporateWebsite.Portal/Views/Product/Category.cshtml
@using OIU.CorporateWebsite.Model
@using OIU.MvcPager
@model PagedList<OIU.CorporateWebsite.Model.Product>

@section head
{@{Html.RegisterMvcPagerCssResource();}}
@{ Html.RenderAction("SiteLeft", "SiteConfig");}

<div class="ccright">
    <div class="ctit3">
        您现在的位置是：<a href="/" target="_blank">首页</a> > @Html.ActionLink("产品展示", "Index", "Product") > @Html.ActionLink(((PCategory)ViewBag.pc).CName, "Category")
        
    </div>
    <div id="productlist" style="padding: 10px 0 10px 15px; line-height: 200%;">
        <ul>
            @foreach (var m in Model)
            {
                <li>
                    <a href="@Url.Action("Details","Product",new{id=m.ID})" class="pimg">
                        <img src="@m.PImg" alt="@m.PName" />
                    </a>
                    @Html.ActionLink(m.PName, "Details", "Product", new { id = m.ID }, new { @class = "pname" })
                </li>
            }
            <div class="clear"></div>
        </ul>

    </div>

    @Html.Pager(Model, new PagerOptions
                            {
                                PageIndexParameterName = "pageIndex",
                                CurrentPagerItemWrapperFormatString = "<span class=\"current\">{0}</span>",
                                AutoHide = false,
                                FirstPageRouteName = "pcategory"
                            }, "pcategoryPage", null,
                       new { id = "badoopager" })

</div>
@section scripts
{@{Html.RegisterMvcPagerScriptResource();}}

OIU.CorporateWebsite.Portal/Views/Product/Details.cshtml
@using OIU.CorporateWebsite.Model
@using OIU.MvcPager
@model OIU.CorporateWebsite.Model.Product

@section head
{
    <script src="~/Content/MVCPager/MvcPager.min.js"></script>
    <link href="~/Content/MVCPager/pagerstyles.min.css" rel="stylesheet" />
}
@{ Html.RenderAction("SiteLeft", "SiteConfig");}
<div class="ccright">
    <div class="ctit3">您现在的位置是：<a href="/" target="_blank">首页</a> > @Html.ActionLink("产品展示", "Index", "Product") > 
        @Html.ActionLink(((PCategory)ViewBag.pc).CName, "Category", new { cid = ((PCategory)ViewBag.pc).ID })</div>
    <div style="padding: 10px 0 10px 15px; line-height: 200%;">

        <div style="background-color: #f2f2f2; text-align: center; margin-bottom: 15px;">
            <h3>@Model.PName</h3>
        </div>

        @Html.Raw(Model.PContent)
        
        
        <div id="productlist" style=" line-height: 200%;">
            <p style="border-bottom: 1px dashed #ccc;">
                <strong>相关产品</strong>
            </p>
            <ul>
                @foreach (var m in ViewBag.prelation as PagedList<Product>)
                {
                    <li>
                        <a href="@Url.Action("Details","Product",new{id=m.ID})" class="pimg">
                            <img src="@m.PImg" alt="@m.PName" />
                        </a>
                        @Html.ActionLink(m.PName, "Details", "Product", new { id = m.ID }, new { @class = "pname" })
                    </li>
                }
                <div class="clear"></div>
            </ul>
            
            @Html.Pager(ViewBag.prelation as PagedList<Product>, new PagerOptions
            {
                PageIndexParameterName = "pageIndex",
                CurrentPagerItemWrapperFormatString = "<span class=\"current\">{0}</span>",
                AutoHide = false,
                FirstPageRouteName = "default"
            }, "detailspager", null,
                new { id = "badoopager" })
        </div>

        
    </div>

</div>
@section scripts
{
    <script type="text/javascript">
        $(function() {
            if ($("#productlist ul li").length == 0) {
                $("#productlist").hide();
            }
        });
    </script>

}

OIU.CorporateWebsite.Portal/Views/Product/Index.cshtml
@using OIU.CorporateWebsite.Model
@using OIU.MvcPager
@model PagedList<OIU.CorporateWebsite.Model.Product>

@section head
{
    <script src="~/Content/MVCPager/MvcPager.min.js"></script>
    <link href="~/Content/MVCPager/pagerstyles.min.css" rel="stylesheet" />
}
@{ Html.RenderAction("SiteLeft", "SiteConfig");}

<div class="ccright">
    <div class="ctit3">您现在的位置是：<a href="/" target="_blank">首页</a> > @Html.ActionLink("产品展示", "Index", "Product") </div>
    <div id="productlist" style="padding: 10px 0 10px 15px; line-height: 200%;">
        <ul>
            @foreach (var m in Model)
            {
                <li>
                    <a href="@Url.Action("Details","Product",new{id=m.ID})" class="pimg">
                        <img src="@m.PImg" alt="@m.PName" />
                    </a>
                    @Html.ActionLink(m.PName, "Details", "Product", new { id = m.ID }, new { @class = "pname" })
                </li>
            }
            <div class="clear"></div>
        </ul>

    </div>

    @Html.Pager(Model, new PagerOptions
                            {
                                PageIndexParameterName = "id",
                                CurrentPagerItemWrapperFormatString = "<span class=\"current\">{0}</span>",
                                AutoHide = false,FirstPageRouteName ="default"
                            }, "pager", null,
                       new { id = "badoopager" })

</div>